### ISSUE TITLE
Need Patater to tell me if I've got NDA right

### ISSUE THREAD

**Issue by StoneCypher** [StoneCypher/jssm#301]
Is this a nondeterministic automaton, @Patater?

```
UnflippedCoin 'Flip Coin' 50% -> Heads;
UnflippedCoin 'Flip Coin' 50% -> Tails;
```

**Comment by Patater** [comment]
Nope. I like the random transitions a lot, but an NFA is a bit different. I'll explain a few properties of NFA below, given some example NFAs.

```
Start 'a' -> Middle
Middle 'b' -> Almost
Middle 'b' -> Almost2
Almost 'd' -> End
Almost2 'c' -> End
```

Whenever there is a choice in path, the NFA takes all paths simultaneously.
So, given input string "abc" or "abd", we can reach End. This is different from picking a choice randomly, as if we were to do so, we'd only sometimes reach End after the input "abc" (maybe only 50% of the time, if two choices are chosen between with even probability).


```
Start 'a' -> Middle
Start2 'x' -> Middle2
Middle 'b' -> Almost
Middle2 'y' -> Almost2
Almost 'c' -> End
Almost2 'z' -> End2
```

NFA can also have multiple start states. NFA can also choose not to take a transition, regardless of if the input character at that step is valid or not. So, input string "aaaabc" will reach End and "aaaxyz" will reach End2. Transitions taken for the first input string would be: `Start->Start->Start->Start->Middle->Almost->End` (or just `Start->Middle->Almost->End`, reflecting that no transition _really_ happened). Transitions taken for the second input string would be: `Start2->Start2->Start2->Start2->Middle2->Almost2->End2` (or just `Start2->Middle2->Almost2->End2`, reflecting that no transition _really_ happened).

A DFA, with these rules, would get stuck and die. Given "aaaabc", the DFA would transition to Middle after the first 'a', and then upon seeing the second 'a', would see it had nowhere to go. No transition is defined from Middle for the input 'a'. As you can hopefully see, this means writing rules for an NFA is a lot easier, because one doesn't have to define all possible transitions from every state explicitly. You could write a DFA that would reach the End state given "aaaabc", but it would be a bit bigger and more complicated, especially if it were to reach End for all inputs that the above NFA would (e.g. "axaxaxyaabc").

Hope this helps!

**Comment by StoneCypher** [comment]
so an NDA is prolog?

it follows every path while maintaining the ability to drop paths which later were proven infeasible?

**Comment by Patater** [comment]
It is all knowing, taking the best path. :)

**Comment by StoneCypher** [comment]
ok so let me make sure i've got this straight

the fundamental problem with FSMs that NDAs solve is that future ambiguity can interact with being partially resolved by things learned in the past, and that in order to generate FSMs which cope with that, you have to explicitly enumerate the interrim possibilities

so NDAs allow you to write simpler rule sets by writing in a way that you can leave the machine ambiguous at midpoints in the sequence, to be resolved later by the machine?

**Comment by StoneCypher** [comment]
Ok.  I think this is probably too big a change for how this library works and I need to decline it

I am thinking about this for a future library though
