### ISSUE TITLE
Huge package

### ISSUE THREAD

**Issue by conartist6** [StoneCypher/jssm#401]
I happened to see this package as I was looking for a state machine implementation. You may notice the NPM reports bundle sizes now, and yours is 25mb. I actually downloaded the package tarball just to see if I should report it as a virus.

Here are things you are currently shipping that you might not want to be:
```
/.rp2t_cache/**
/docs/**
/src/**
/.github/**
/notes/**
.nycrc
.eslintrc
.editorconfig
```

Of course, much easier would be to set the package `files` field to just be `/dist/**`

**Comment by StoneCypher** [comment]
oh holy crap.  thank you for letting me know

**Comment by StoneCypher** [comment]
Okay. 

So the first 11 meg were map files.  That was easy enough to remove.

The next 15?  My.  Seems `peg` was blowing my 34k grammar up to a 3.7 meg parser.  Also, y'know, I have three copies in the repo - es6, es5 commonjs, and es5 iife.

And, fun: `typescript` doesn't like the output when I set it to `optimize size` instead of `optimize speed`.

Will look more into it.

Released one that's got 40% of the problem solved so far.

Thinking about dropping the `cjs` build now that node has es6

**Comment by StoneCypher** [comment]
Okay.

I've removed most of the files from the `npm` package now.  There was a build product getting into the package that I hadn't seen.

I've replaced everything in the `npm` package with minified.  The non-minified are still present after a local build, but now under the name `*.nonmin.*`.

That drops us, since we still have three builds in the repo, to 1.5 meg

Still much too large, but, a 94% drop, so, good first steps.

**Comment by StoneCypher** [comment]
Right now about half of the `npm` package is images from the source-extracted documentation

I'm gonna see what I can do about getting a plugin together for my documentation extractor so that I can just use [jssm-viz](https://github.com/StoneCypher/jssm-viz) on the fly in the build process and not actually need to ship the images

OTOH that might actually end up being larger than the images.  There's a transcompile of graphviz in there, and graphviz isn't svelte

**Comment by conartist6** [comment]
Haha yep that sounds a lot better. By the way, I don't know if you'll be interested but I was looking at state machines because I'm working on a new parser. The idea is to trade some perf in order to avoid any compilation steps and reduce the ultimate bundle size.

**Comment by StoneCypher** [comment]
a new parser like to replace peg, you mean?

**Comment by StoneCypher** [comment]
or, to replace jssm (the machine impl) to otherwise handle fsl (the language), instead?

**Comment by conartist6** [comment]
An alternative to peg, yes.

**Comment by StoneCypher** [comment]
I mean I tried a couple others, and even made some headway with canopy, which was exciting because that was potentially cross-language

it turned out to be really quite difficult though

**Comment by conartist6** [comment]
I'm building off [my fork of rd-parse](https://github.com/conartist6/rd-parse#usage). Currently working on adding a new [lexer API](https://gist.github.com/conartist6/a1b9e644a5934f059a1a1fd5b8848a20)

**Comment by StoneCypher** [comment]
oh this is a whole different kind of parser

**Comment by conartist6** [comment]
indeed

**Comment by conartist6** [comment]
It's not ready for adoption yet, I'm more just curious to hear if you think something like this would solve any problems you have..?

**Comment by StoneCypher** [comment]
ya i think bailing on packrat grammars is probably more than i'm looking for at this time.  this project has a whole lot invested in this style of parsing

this does look like a neat parser though and i'll try it in other new projects.  i parse a lot

**Comment by StoneCypher** [comment]
converting [a grammar like this one](https://github.com/StoneCypher/jssm/blob/master/src/js/jssm-dot.peg) would take a long time, and getting it to match a test set like this one, afterwards, would be brutal:

```
  2494 tests passed

---------------------------|---------|----------|---------|---------|-------------------
File                       | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
---------------------------|---------|----------|---------|---------|-------------------
All files                  |     100 |      100 |     100 |     100 |
```

**Comment by conartist6** [comment]
Hmm, well thanks for that link. I learned some things, like that I should consider memoizing my results. But I think what I'm making is still formally the same kind of parser. It just uses code for the grammar, thus I don't think it would necessarily be awful to convert. Much of it translates directly in fact.

I can even see some definite potential wins. For example because your syntax is expressed as code, you could easily import these constant mappings (like named colors) from someplace where they are predefined. And having a separate tokenization phase would eliminate the problems you seem to be having when some named constants are prefixes of others.

**Comment by conartist6** [comment]
I'm mostly thinking of javascript syntax as I build so perhaps once I get a bit further I'll try to port your syntax just to see if what I've build is powerful enough. Also helpful that you have a huge test suite so I'd know if I've done it right : )

**Comment by StoneCypher** [comment]
You're right.

`files` is now 

```
  "files": [
    "dist/jssm.es5.cjs.js",
    "dist/es6/version.js",
    "**/*.d.ts",
    "CHANGELOG.md"
  ],
```

Changelog's just for debugging

**Comment by StoneCypher** [comment]
That's got unpacked size down to 658k, which covers es5 cjs and es6.

That feel good to you for a close, @conartist6 ?

**Comment by StoneCypher** [comment]
next stop: the visualizer

![image](https://user-images.githubusercontent.com/77482/79079718-83365900-7cc5-11ea-9282-63ed680c3aac.png)

**Comment by StoneCypher** [comment]
@conartist6 - I'm going to close this because it's dropped my quality rating by 30% that it's been open so long

TYVM.  Please open another issue if you see other things

**Comment by StoneCypher** [comment]
@conartist6 - Just FYI, I had to switch to `.npmignore` instead of `files` as the mechanism, because for reasons I haven't figured out yet, `files` tanked my `npm` quality score by 30%

**Comment by conartist6** [comment]
Oh weird. Yeah I was going to say that I didn't think keeping a single issue open could do that. I'm still mystified as to how `files` could do that either. Glad you figured it out thought.

**Comment by StoneCypher** [comment]
It's well known that the number of issues and their age is a factor in the old `npms.io` algorithm.  That's why I transitioned all my issues [to a different repo](https://github.com/StoneCypher/fsl/issues/).

You can see it in [the api response for a different repo](https://api.npms.io/v2/package/fsl) (warning, large unformatted json).  I use the `fsl` repo for the example instead of the `jssm` repo because since the `jssm` repo now has no relevant issues, the section is removed.

The two relevant pieces are the `maintenance` section and the `github` breakdown:

```
    "evaluation":{
        "quality":{
            "carefulness":0.192075,
            "tests":0,
            "health":1,
            "branding":0
        },
        "popularity":{
            "communityInterest":9,
            "downloadsCount":8.333333333333334,
            "downloadsAcceleration":-0.03247716894977169,
            "dependentsCount":0
        },
        "maintenance":{
            "releasesFrequency":0,
            "commitsFrequency":0.011506849315068493,
            "openIssues":0.1772908366533864,
            "issuesDistribution":0
        }
    },
```

and

```json
        "github":{
            "starsCount":5,
            "forksCount":1,
            "subscribersCount":2,
            "issues":{
                "count":502,
                "openCount":413,
                "distribution":{
                    "3600":24,
                    "10800":11,
                    "32400":6,
                    "97200":1,
                    "291600":10,
                    "874800":10,
                    "2624400":4,
                    "7873200":206,
                    "23619600":36,
                    "70858800":194,
                    "212576400":0
                },
                "isDisabled":false
            },
```

The NPM algorithm is relatively simple: a score is the weighted average of components, themselves often nested averages.

`maintenance`, the section in question, has a 35% weight on the master score, and `openIssues` is 20% of `maintenance`.  The `fsl` repo is scored `0.17` on `openIssues`, meaning those gh issues alone drag the total score down by 7% from an ideal `1.0`.

@conartist6 - frankly I think it's a stupid system
