### ISSUE TITLE
Parse the JSSM format

### ISSUE THREAD

**Issue by thelinuxlich** [StoneCypher/jssm#434]
I'd like to use this library to implement graphql mutations based on the state machine (https://github.com/rel-js/rel/issues/22) is there a helper function that gets the parsed structure so I can do that?

**Comment by StoneCypher** [comment]
Yeah, I think you probably want `.parse/1`.  There's a couple different routes

Generally, it seems likely that emitting the JSON representation is likely to be your easiest integration approach.  There exist alternatives

```typescript
const as_json = jssm.parse( your_machine_string );
```

![image](https://user-images.githubusercontent.com/77482/147778179-e4286209-4c60-47ab-976d-f05df93ae1b7.png)

I want to point out one slightly inobvious thing about the JSON representation as long as I have you here: note how it represents the second statement, where more than one rule is chained (because I see that you intend to use that.)

The second edge is returned as a child of the first edge.  That's not immediately obvious sometimes. 

You could, if you prefer, fully manufacture the machine, and then interrogate it directly.  This is more appropriate if you want to get subgraphs, such as "the portion of the machine attached to this state here."  You would do that with `.states()` and `.list_edges()`, and possibly with `.actions()` if you're using them, after generating the machine, which is easiest done with the `sm\`\`` template constructor:

![image](https://user-images.githubusercontent.com/77482/147778628-2bad19f6-a20f-4e85-b32a-1219757d7c8e.png)

But I think probably just eating the JSON from `.parse` is easiest

There's other stuff you can use in the `Machine` api too: https://stonecypher.github.io/jssm/docs/classes/Machine.html

**Comment by thelinuxlich** [comment]
Great, I think I have everything I need here

**Comment by StoneCypher** [comment]
@thelinuxlich - mind if i close this?  i just realized it's still open

**Comment by thelinuxlich** [comment]
Sure!
